language: cpp
compiler: gcc
os: linux
dist: xenial
addons:
    apt:
        packages:
            - cmake
            - cmake-data

script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
    - make test
